wandb_version: 1

learning_rate:
  desc: null
  value: 0.001
epochs:
  desc: null
  value: 1000
_wandb:
  desc: null
  value:
    python_version: 3.11.9
    cli_version: 0.17.9
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1725574070
    t:
      1:
      - 1
      - 55
      - 105
      2:
      - 1
      - 55
      - 105
      3:
      - 16
      - 23
      4: 3.11.9
      5: 0.17.9
      8:
      - 4
      - 5
      13: darwin-arm64
